// ============================================================
// Austin Treasure Map — Place Data & Category Definitions
// All 88 places with verified GPS coordinates
// ============================================================

export const CATEGORIES = {
  food:       { label: 'Food & Restaurants', icon: '🍽️', color: '#c4883c' },
  bars:       { label: 'Bars & Nightlife',   icon: '🥃', color: '#8b4513' },
  coffee:     { label: 'Coffee & Tea',       icon: '☕', color: '#5d4037' },
  nature:     { label: 'Nature & Outdoors',  icon: '🌿', color: '#2d5016' },
  icecream:   { label: 'Ice Cream & Sweets', icon: '🍦', color: '#e91e63' },
  music:      { label: 'Music & Entertainment', icon: '🎵', color: '#6b3074' },
  culture:    { label: 'Culture & Museums',  icon: '🏛️', color: '#1a237e' },
  shopping:   { label: 'Shopping & Vintage', icon: '🛍️', color: '#b71c1c' },
  unique:     { label: 'Unique & Quirky',    icon: '⭐', color: '#ff8f00' },
};

export const PLACES = [

  // ─── FOOD & RESTAURANTS (33) ────────────────────────────────

  {
    id: 'buddha-burger',
    name: 'Buddha Burger',
    lat: 30.4060, lng: -97.6975,
    category: 'food',
    neighborhood: 'North Austin',
    address: '12195 Metric Blvd, Austin, TX 78758',
    description: 'Gourmet burgers with creative toppings. North Austin hidden gem.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'curras-hyde-park',
    name: "Curra's Hyde Park",
    lat: 30.3039, lng: -97.7265,
    category: 'food',
    neighborhood: 'Hyde Park',
    address: '4215 Duval St, Austin, TX 78751',
    description: 'Famous avocado margaritas and frozen margaritas. Interior Mexican.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'grannys-tacos',
    name: "Granny's Tacos",
    lat: 30.2643, lng: -97.7281,
    category: 'food',
    neighborhood: 'East Austin',
    address: '1401 E 7th St, Austin, TX 78702',
    description: 'Breakfast tacos done right. East Austin staple.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'mama-bettys',
    name: "Mama Betty's Tex-Mex",
    lat: 30.4860, lng: -97.7704,
    category: 'food',
    neighborhood: 'North Austin',
    address: '9900 W Parmer Ln #220, Austin, TX 78717',
    description: 'Tex-Mex with mesquite-grilled fajitas. Worth the drive north.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'ramen-del-barrio',
    name: 'Ramen Del Barrio',
    lat: 30.4129, lng: -97.6869,
    category: 'food',
    neighborhood: 'North Austin',
    address: '2007 Kramer Ln #105, Austin, TX 78758',
    description: 'Michelin Bib Gourmand. Asian-Mexican fusion ramen — unlike anything else.',
    source: 'social media',
    dayTrip: false,
  },
  {
    id: 'casa-de-luz',
    name: 'Casa de Luz',
    lat: 30.2644, lng: -97.7616,
    category: 'food',
    neighborhood: 'Zilker',
    address: '1701 Toomey Rd, Austin, TX 78704',
    description: 'No menu, no seasoning, 3rd space. 100% organic vegan community dining.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'asia-cafe',
    name: 'Asia Cafe',
    lat: 30.4323, lng: -97.7708,
    category: 'food',
    neighborhood: 'North Austin',
    address: '8650 Spicewood Springs Rd #114A, Austin, TX 78759',
    description: 'Authentic Sichuan Chinese. The mapo tofu and dry pot are legendary.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: '888-pan-asian',
    name: '888 Pan Asian',
    lat: 30.2292, lng: -97.7300,
    category: 'food',
    neighborhood: 'South Austin',
    address: '2400 E Oltorf St #1A, Austin, TX 78741',
    description: 'Vietnamese/Thai/Chinese. Expect waits — it\'s that good.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'chalmers',
    name: 'Chalmers',
    lat: 30.2579, lng: -97.7266,
    category: 'food',
    neighborhood: 'East Austin',
    address: '1700 E Cesar Chavez St, Austin, TX 78702',
    description: 'West Texas icehouse + live music. East Austin vibes.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'old-alley-hot-pot',
    name: 'Old Alley Hot Pot',
    lat: 30.3984, lng: -97.7045,
    category: 'food',
    neighborhood: 'North Austin',
    address: '11900 Metric Blvd #F, Austin, TX 78758',
    description: 'Sichuan hot pot with Kobe beef and lobster. Premium experience.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'eldorado-cafe',
    name: 'Eldorado Cafe',
    lat: 30.3623, lng: -97.7423,
    category: 'food',
    neighborhood: 'Allandale',
    address: '3300 W Anderson Ln #303, Austin, TX 78757',
    description: 'Mexican/Tex-Mex comfort food. Neighborhood favorite.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'kiin-di',
    name: 'Kiin Di',
    lat: 30.2469, lng: -97.7774,
    category: 'food',
    neighborhood: 'South Lamar',
    address: '2414 S Lamar Blvd #A, Austin, TX 78704',
    description: 'Thai food on South Lamar. Pad see ew and curries.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'lucys-fried-chicken',
    name: "Lucy's Fried Chicken",
    lat: 30.2403, lng: -97.7533,
    category: 'food',
    neighborhood: 'South Congress',
    address: '2218 College Ave, Austin, TX 78704',
    description: 'Iconic Austin fried chicken. Great patio, cold beer, hot bird.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'gourdoughs',
    name: "Gourdough's",
    lat: 30.2497, lng: -97.7547,
    category: 'food',
    neighborhood: 'South First',
    address: '1503 S 1st St, Austin, TX 78704',
    description: 'Gourmet donuts from an Airstream trailer. Over-the-top toppings.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'p-thais-khao-man-gai',
    name: "P Thai's Khao Man Gai",
    lat: 30.3087, lng: -97.7153,
    category: 'food',
    neighborhood: 'Hyde Park',
    address: '4807 Airport Blvd, Austin, TX 78751',
    description: 'Thai chicken rice. Simple, perfect, comforting.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'pho-dan',
    name: 'Pho Dan',
    lat: 30.3810, lng: -97.6869,
    category: 'food',
    neighborhood: 'North Austin',
    address: '11220 N Lamar Blvd #B-200, Austin, TX 78753',
    description: 'Vietnamese pho specialist. Big bowls, authentic broth.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'mam-mam',
    name: 'Mam Mam',
    lat: 30.2672, lng: -97.6925,
    category: 'food',
    neighborhood: 'East Austin',
    address: '1023 Springdale Rd Bldg 1, Austin, TX 78721',
    description: 'Asian comfort food in East Austin. Creative fusion menu.',
    source: 'social media',
    dayTrip: false,
  },
  {
    id: 'fresas',
    name: "Fresa's",
    lat: 30.2478, lng: -97.7553,
    category: 'food',
    neighborhood: 'South First',
    address: '1703 S 1st St, Austin, TX 78704',
    description: 'Wood-grilled chicken, Mexican-inspired. Great al fresco dining.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'el-meson',
    name: 'El Meson Tequileria',
    lat: 30.2488, lng: -97.7689,
    category: 'food',
    neighborhood: 'South Lamar',
    address: '2038 S Lamar Blvd, Austin, TX 78704',
    description: 'Interior Mexican (not Tex-Mex). Incredible mole dishes.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'cuantos-tacos',
    name: 'Cuantos Tacos',
    lat: 30.2728, lng: -97.7282,
    category: 'food',
    neighborhood: 'East Austin',
    address: '1108 E 12th St, Austin, TX 78702',
    description: 'Michelin-recognized tacos. East Austin treasure.',
    source: 'social media',
    dayTrip: false,
  },
  {
    id: 'taqueria-guadalajara',
    name: 'Taqueria Guadalajara',
    lat: 30.3416, lng: -97.7392,
    category: 'food',
    neighborhood: 'Burnet Road',
    address: '6534 Burnet Rd, Austin, TX 78757',
    description: 'Mexican comfort food. Breakfast tacos that\'ll change your life.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'ho-ho-chinese-bbq',
    name: 'Ho Ho Chinese BBQ',
    lat: 30.3967, lng: -97.6781,
    category: 'food',
    neighborhood: 'North Austin',
    address: '13000 N IH-35 Bldg 6, Austin, TX 78753',
    description: 'Cantonese BBQ + live seafood tanks. The roast duck is unreal.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'snooze',
    name: 'Snooze AM Eatery',
    lat: 30.3088, lng: -97.7509,
    category: 'food',
    neighborhood: 'Hyde Park',
    address: '3800 N Lamar Blvd #120, Austin, TX 78756',
    description: 'Brunch/breakfast spot. Pancake flights and benedicts.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'bird-bird-biscuit',
    name: 'Bird Bird Biscuit',
    lat: 30.2850, lng: -97.7140,
    category: 'food',
    neighborhood: 'Mueller',
    address: '2701 Manor Rd, Austin, TX 78722',
    description: 'Fried chicken biscuit sandwiches. The Nelly is iconic.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'moonshine',
    name: 'Moonshine Patio Bar & Grill',
    lat: 30.2637, lng: -97.7384,
    category: 'food',
    neighborhood: 'Downtown',
    address: '303 Red River St, Austin, TX 78701',
    description: 'Southern comfort in an 1850s limestone building. Great brunch.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'cosmic-coffee',
    name: 'Cosmic Coffee + Beer Garden',
    lat: 30.2268, lng: -97.7625,
    category: 'food',
    neighborhood: 'South Austin',
    address: '121 Pickle Rd #111, Austin, TX 78704',
    description: 'Coffee + beer + food trucks + lush garden. Ultimate hangout.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'kesos-tacos',
    name: 'Kesos Tacos',
    lat: 30.2754, lng: -97.7478,
    category: 'food',
    neighborhood: 'Downtown',
    address: '600 W MLK Jr Blvd, Austin, TX 78701',
    description: 'Tex-Mex tacos near campus. Quick, cheap, delicious.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'joes-bakery',
    name: "Joe's Bakery",
    lat: 30.2611, lng: -97.7167,
    category: 'food',
    neighborhood: 'East Austin',
    address: '2305 E 7th St, Austin, TX 78702',
    description: 'Legendary East Austin Mexican bakery since 1962. Pan dulce heaven.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'sushi-warriors',
    name: 'Sushi Warriors',
    lat: 30.3116, lng: -97.7384,
    category: 'food',
    neighborhood: 'Hyde Park',
    address: '4600 W Guadalupe St #B5, Austin, TX 78751',
    description: 'All-you-can-eat sushi at The Triangle. Solid quality.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'dk-sushi',
    name: 'DK Sushi / Seoul Korean',
    lat: 30.2003, lng: -97.7862,
    category: 'food',
    neighborhood: 'South Austin',
    address: '6400 S 1st St #C, Austin, TX 78745',
    description: 'Oldest sushi bar in Austin (1993). Korean + Japanese.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'sushi-junai',
    name: 'Sushi Junai',
    lat: 30.2790, lng: -97.7416,
    category: 'food',
    neighborhood: 'Downtown',
    address: '1612 Lavaca St, Austin, TX 78701',
    description: 'All-you-can-eat sushi downtown. Buzzy atmosphere.',
    source: 'social media',
    dayTrip: false,
  },
  {
    id: 'avenue-b-grocery',
    name: 'Avenue B Grocery',
    lat: 30.3090, lng: -97.7314,
    category: 'food',
    neighborhood: 'Hyde Park',
    address: '4403 Avenue B, Austin, TX 78751',
    description: 'Oldest grocery store in Austin (1909). Hyde Park landmark, great sandwiches.',
    source: 'personal exploration',
    dayTrip: false,
  },

  // ─── BARS & NIGHTLIFE (13) ──────────────────────────────────

  {
    id: 'equipment-room',
    name: 'Equipment Room',
    lat: 30.2517, lng: -97.7497,
    category: 'bars',
    neighborhood: 'Bouldin Creek',
    address: '1101 Music Ln, Austin, TX 78704',
    description: 'Speakeasy + jazz bar hidden inside Hotel Magdalena. Lake Austin Blvd vibes.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'red-headed-stepchild',
    name: 'Red Headed Stepchild',
    lat: 30.2668, lng: -97.7420,
    category: 'bars',
    neighborhood: 'Downtown',
    address: '119 E 5th St, Austin, TX 78701',
    description: 'Hidden speakeasy. Monthly code to enter. Ask around or check social media.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'kellys-irish-pub',
    name: "Kelly's Irish Pub",
    lat: 30.2427, lng: -97.7573,
    category: 'bars',
    neighborhood: 'South Austin',
    address: '519 W Oltorf St, Austin, TX 78704',
    description: 'Irish pub in South Austin. Cozy, unpretentious.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'shandeez-grill',
    name: 'Shandeez Grill',
    lat: 30.4530, lng: -97.8060,
    category: 'bars',
    neighborhood: 'North Austin',
    address: '8863 Anderson Mill Rd, Austin, TX',
    description: 'Persian restaurant. Kebabs, stews, and saffron rice.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'tiger-lilly',
    name: 'Tiger Lilly',
    lat: 30.2666, lng: -97.7459,
    category: 'bars',
    neighborhood: 'Downtown',
    address: '400 Colorado St, Austin, TX 78701',
    description: 'Friday jazz nights. 50% off martinis 5-9pm. Classy downtown vibes.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'latchkey',
    name: 'Latchkey',
    lat: 30.2640, lng: -97.7287,
    category: 'bars',
    neighborhood: 'East Austin',
    address: '1308 E 6th St, Austin, TX 78702',
    description: 'Dive bar on East 6th. Cheap drinks, good music, solid crowd.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'vigilante',
    name: 'Vigilante Gastropub',
    lat: 30.3428, lng: -97.7172,
    category: 'bars',
    neighborhood: 'North Loop',
    address: '7010 Easy Wind Dr #150, Austin, TX 78752',
    description: 'Gaming bar + board games + pinball. Nerd paradise with craft beer.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'mean-eyed-cat',
    name: 'Mean Eyed Cat',
    lat: 30.2745, lng: -97.7650,
    category: 'bars',
    neighborhood: 'Clarksville',
    address: '1621 W 5th St, Austin, TX 78703',
    description: 'Johnny Cash themed dive bar. Patio, cold beer, Austin classic.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'travelers-lounge',
    name: 'Travelers Lounge',
    lat: 30.2596, lng: -97.6969,
    category: 'bars',
    neighborhood: 'East Austin',
    address: '5012 E 7th St, Austin, TX 78702',
    description: 'Space-themed bus speakeasy in deep East Austin. Truly one of a kind.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'milonga-room',
    name: 'Milonga Room',
    lat: 30.2639, lng: -97.7280,
    category: 'bars',
    neighborhood: 'East Austin',
    address: '1201 E 6th St, Austin, TX 78702',
    description: '1920s Argentine speakeasy under Buenos Aires Cafe. Intimate, candlelit.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'holey-moley',
    name: 'Holey Moley Golf Club',
    lat: 30.2652, lng: -97.7187,
    category: 'bars',
    neighborhood: 'East Austin',
    address: '807 E 4th St, Austin, TX 78702',
    description: 'Indoor mini golf bar + karaoke. Themed holes are hilarious.',
    source: 'social media',
    dayTrip: false,
  },

  // ─── COFFEE & TEA (4) ──────────────────────────────────────

  {
    id: 'stargazer',
    name: 'Stargazer',
    lat: 30.2631, lng: -97.7005,
    category: 'coffee',
    neighborhood: 'East Austin',
    address: '979 Springdale Rd #130, Austin, TX 78702',
    description: 'Coffee AM, cocktails PM. Gorgeous East Austin space.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'a-hole-coffee',
    name: 'A Hole Coffee',
    lat: 30.2626, lng: -97.7186,
    category: 'coffee',
    neighborhood: 'East Austin',
    address: '2312 Morelos St, Austin, TX 78702',
    description: "Coffee served through a literal hole in the wall. That's the whole concept.",
    source: 'social media',
    dayTrip: false,
  },
  {
    id: 'west-china-tea',
    name: 'West China Tea House',
    lat: 30.2636, lng: -97.7250,
    category: 'coffee',
    neighborhood: 'East Austin',
    address: '1715 E 7th St, Austin, TX 78702',
    description: 'Gong fu cha ceremony. Artisan Chinese tea in a peaceful setting.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'first-light-books',
    name: 'First Light Books',
    lat: 30.3070, lng: -97.7299,
    category: 'coffee',
    neighborhood: 'Hyde Park',
    address: '4300 Speedway, Austin, TX 78751',
    description: 'Bookshop + cafe in Hyde Park. Browse, sip, stay a while.',
    source: 'personal exploration',
    dayTrip: false,
  },

  // ─── ICE CREAM & SWEETS (2) ────────────────────────────────

  {
    id: 'dolce-neve',
    name: 'Dolce Neve',
    lat: 30.2476, lng: -97.7555,
    category: 'icecream',
    neighborhood: 'South First',
    address: '1713 S 1st St, Austin, TX 78704',
    description: 'Authentic Italian gelato. Pistachio and stracciatella are unreal.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'zeds-ice-cream',
    name: "Zed's Real Fruit Ice Cream",
    lat: 30.2821, lng: -97.7057,
    category: 'icecream',
    neighborhood: 'East Austin',
    address: '1814 Harvey St, Austin, TX 78702',
    description: 'Fresh real fruit ice cream made to order. Pure and vibrant flavors.',
    source: 'social media',
    dayTrip: false,
  },

  // ─── NATURE & OUTDOORS (12) ─────────────────────────────────

  {
    id: 'mount-bonnell',
    name: 'Mount Bonnell',
    lat: 30.3210, lng: -97.7736,
    category: 'nature',
    neighborhood: 'West Austin',
    address: '3800 Mount Bonnell Rd, Austin, TX 78731',
    description: "Austin's highest point. 102 steps up for panoramic Lake Austin views.",
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'hamilton-pool',
    name: 'Hamilton Pool Preserve',
    lat: 30.3423, lng: -98.1269,
    category: 'nature',
    neighborhood: 'Dripping Springs',
    address: '24300 Hamilton Pool Rd, Dripping Springs, TX',
    description: '50ft waterfall into a natural pool. Reservation required. Worth the drive.',
    source: 'word of mouth',
    dayTrip: true,
  },
  {
    id: 'jessica-hollis-park',
    name: 'Jessica Hollis Park',
    lat: 30.3866, lng: -97.9096,
    category: 'nature',
    neighborhood: 'West Austin',
    address: '14100 Low Water Crossing Rd, Austin, TX 78732',
    description: 'LCRA park on Lake Austin. Quiet, scenic, less crowded.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'the-lookout',
    name: 'The Lookout (Pennybacker)',
    lat: 30.3494, lng: -97.7967,
    category: 'nature',
    neighborhood: 'West Austin',
    address: 'N Capital of TX Hwy (Loop 360), Austin, TX',
    description: 'Iconic bridge overlook. Best sunset spot in Austin.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'hippie-hollow',
    name: 'Hippie Hollow',
    lat: 30.4132, lng: -97.8841,
    category: 'nature',
    neighborhood: 'West Austin',
    address: '7000 Comanche Trail, Austin, TX 78732',
    description: 'Clothing-optional park on Lake Travis. Only one in Texas.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'krause-springs',
    name: 'Krause Springs',
    lat: 30.4776, lng: -98.1516,
    category: 'nature',
    neighborhood: 'Spicewood',
    address: '424 CR 404, Spicewood, TX 78669',
    description: '32 natural springs. Swimming, camping, butterfly gardens.',
    source: 'word of mouth',
    dayTrip: true,
  },
  {
    id: 'pfluger-bridge',
    name: 'Pfluger Pedestrian Bridge',
    lat: 30.2636, lng: -97.7536,
    category: 'nature',
    neighborhood: 'Zilker',
    address: 'Lady Bird Lake Trail, Austin, TX',
    description: 'Steel pedestrian bridge on Lady Bird Lake. Hike & bike trail staple.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'hill-of-life',
    name: 'Hill of Life / Dam of Life',
    lat: 30.2890, lng: -97.8100,
    category: 'nature',
    neighborhood: 'West Austin',
    address: '1710 Camp Craft Rd, Austin, TX 78746',
    description: 'Steepest Greenbelt section + swimming hole at the bottom. Earn your swim.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'enchanted-rock',
    name: 'Enchanted Rock',
    lat: 30.4960, lng: -98.8200,
    category: 'nature',
    neighborhood: 'Fredericksburg',
    address: '16710 Ranch Rd 965, Fredericksburg, TX 78624',
    description: '425ft pink granite dome. 1.5 hours west of Austin. Reservations required.',
    source: 'personal exploration',
    dayTrip: true,
  },
  {
    id: 'barton-hills-gus-fruh',
    name: 'Barton Hills / Gus Fruh',
    lat: 30.2570, lng: -97.7770,
    category: 'nature',
    neighborhood: 'Barton Hills',
    address: '2632 Barton Hills Dr, Austin, TX 78704',
    description: 'Greenbelt overlook + swimming hole. Local favorite.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'greenbelt-bluff',
    name: 'Greenbelt Bluff View',
    lat: 30.2575, lng: -97.7780,
    category: 'nature',
    neighborhood: 'Barton Hills',
    address: '2632 Barton Hills Dr, Austin, TX 78704',
    description: 'Go right at the trailhead for bluff views along the creek.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'dt-parking-garage',
    name: 'DT Parking Garage Overlook',
    lat: 30.2610, lng: -97.7500,
    category: 'nature',
    neighborhood: 'Downtown',
    address: 'Long Center area, Austin, TX',
    description: 'Rooftop skyline views at sunset. Secret downtown spot.',
    source: 'word of mouth',
    dayTrip: false,
  },

  // ─── MUSIC & ENTERTAINMENT (6) ─────────────────────────────

  {
    id: 'c-boys-heart-soul',
    name: "C-Boy's Heart & Soul",
    lat: 30.2436, lng: -97.7522,
    category: 'music',
    neighborhood: 'South Congress',
    address: '2008 S Congress Ave, Austin, TX 78704',
    description: 'Live soul, blues, and R&B 7 nights a week. Austin institution.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'continental-club',
    name: 'Continental Club',
    lat: 30.2505, lng: -97.7491,
    category: 'music',
    neighborhood: 'South Congress',
    address: '1315 S Congress Ave, Austin, TX 78704',
    description: 'Iconic since 1955. Historic Austin music landmark. No cover most nights.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'live-oak-brewing',
    name: 'Live Oak Brewing',
    lat: 30.2209, lng: -97.6610,
    category: 'music',
    neighborhood: 'East Austin',
    address: '1615 Crozier Ln, Del Valle, TX 78617',
    description: 'German/Czech lagers on 22 acres. Beautiful biergarten.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'aapw-wrestling',
    name: 'AAPW Wrestling',
    lat: 30.3430, lng: -97.6800,
    category: 'music',
    neighborhood: 'North Austin',
    address: '1702 Aldridge Dr #A2, Austin, TX 78754',
    description: 'Pro wrestling school + live shows. Chaotic, fun, unexpected.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'austin-blades',
    name: 'Austin Blades',
    lat: 30.3570, lng: -97.7420,
    category: 'music',
    neighborhood: 'Allandale',
    address: 'Chaparral Ice, 2525 W Anderson Ln, Austin, TX',
    description: 'Sled hockey at Northcross. Adaptive athletics, incredible community.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'stars-stripes-drivein',
    name: 'Stars & Stripes Drive-In',
    lat: 29.7310, lng: -98.1060,
    category: 'music',
    neighborhood: 'New Braunfels',
    address: '1178 Kroesche Ln, New Braunfels, TX',
    description: '3-screen drive-in theater. Double features under the stars.',
    source: 'word of mouth',
    dayTrip: true,
  },

  // ─── CULTURE & MUSEUMS (4) ──────────────────────────────────

  {
    id: 'elisabet-ney',
    name: 'Elisabet Ney Museum',
    lat: 30.3069, lng: -97.7263,
    category: 'culture',
    neighborhood: 'Hyde Park',
    address: '304 E 44th St, Austin, TX 78751',
    description: "19th-century sculptor's studio in Hyde Park. Closed for renovation until Summer 2026.",
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'warren-wildlife',
    name: 'Warren Wildlife Gallery',
    lat: 30.2450, lng: -97.7600,
    category: 'culture',
    neighborhood: 'Bouldin Creek',
    address: '1401 Bouldin Ave, Austin, TX 78704',
    description: '2,300+ taxidermy specimens in South Austin. Jaw-dropping collection.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'we-luv-video',
    name: 'We Luv Video',
    lat: 30.3190, lng: -97.7220,
    category: 'culture',
    neighborhood: 'North Loop',
    address: '100 N Loop Blvd E, Austin, TX 78751',
    description: 'Nonprofit video rental + microcinema. Time capsule of physical media.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'aqua-dome',
    name: 'Austin Aqua-Dome',
    lat: 30.2380, lng: -97.7730,
    category: 'culture',
    neighborhood: 'South Lamar',
    address: '1604 Fortview Rd, Austin, TX 78704',
    description: 'Tropical fish store in a blue dome building. Surreal and beautiful.',
    source: 'word of mouth',
    dayTrip: false,
  },

  // ─── SHOPPING & VINTAGE (7) ─────────────────────────────────

  {
    id: 'antique-gallery-rr',
    name: 'Antique Gallery Round Rock',
    lat: 30.4930, lng: -97.6800,
    category: 'shopping',
    neighborhood: 'Round Rock',
    address: '1601 S IH-35 #400, Round Rock, TX',
    description: 'Massive antique mall. Hundreds of booths. Plan to spend hours.',
    source: 'word of mouth',
    dayTrip: true,
  },
  {
    id: 'out-of-the-past',
    name: 'Out of the Past',
    lat: 30.3270, lng: -97.7400,
    category: 'shopping',
    neighborhood: 'Allandale',
    address: '5341 Burnet Rd, Austin, TX 78756',
    description: 'Vintage toys, records, and collectibles. Burnet Rd gem.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'save-the-good-stuff',
    name: 'Save The Good Stuff',
    lat: 30.3060, lng: -97.7240,
    category: 'shopping',
    neighborhood: 'Hyde Park',
    address: '3908 Avenue B #101, Austin, TX 78751',
    description: 'Architectural salvage in a 1911 schoolhouse. Unique finds.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'use2',
    name: 'USE2',
    lat: 30.2450, lng: -97.7680,
    category: 'shopping',
    neighborhood: 'South Lamar',
    address: '2311 Thornton Rd #O, Austin, TX 78704',
    description: 'Low-cost reuse store. Building materials, furniture, treasures.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'callahans',
    name: "Callahan's General Store",
    lat: 30.2350, lng: -97.7030,
    category: 'shopping',
    neighborhood: 'East Austin',
    address: '501 S Hwy 183, Austin, TX 78741',
    description: 'Austin institution since 1978. Boots, hats, feed, and character.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'kerbey-lane-village',
    name: 'Kerbey Lane Village',
    lat: 30.3060, lng: -97.7520,
    category: 'shopping',
    neighborhood: 'Hyde Park',
    address: '1515 W 35th St, Austin, TX 78703',
    description: 'Outdoor shopping center with local boutiques and eateries.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'dylan-wylde',
    name: 'Dylan Wylde',
    lat: 30.2439, lng: -97.7866,
    category: 'shopping',
    neighborhood: 'South Lamar',
    address: '2324 S Lamar Blvd #B, Austin, TX 78704',
    description: "Women's clothing boutique. Local Austin designer.",
    source: 'word of mouth',
    dayTrip: false,
  },

  // ─── UNIQUE & QUIRKY (7) ────────────────────────────────────

  {
    id: 'austin-six',
    name: 'Austin Six',
    lat: 30.2310, lng: -97.7190,
    category: 'unique',
    neighborhood: 'South Austin',
    address: '521 Thompson Ln, Austin, TX 78742',
    description: 'Adult entertainment venue. Open 24/7.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'aqua-thrill-way',
    name: 'Aqua Thrill Way',
    lat: 30.1940, lng: -97.7340,
    category: 'unique',
    neighborhood: 'South Austin',
    address: '7901 S IH-35, Austin, TX 78744',
    description: 'Abandoned 1978 water park ruins. Urban exploration vibes.',
    source: 'social media',
    dayTrip: false,
  },
  {
    id: 'northcross-mall',
    name: 'Northcross Mall',
    lat: 30.3570, lng: -97.7420,
    category: 'unique',
    neighborhood: 'Allandale',
    address: '2525 W Anderson Ln, Austin, TX 78757',
    description: 'Former mall with Chaparral Ice still operating. Retro Austin.',
    source: 'personal exploration',
    dayTrip: false,
  },
  {
    id: 'practice-yoga',
    name: 'Practice Yoga Austin',
    lat: 30.2650, lng: -97.7310,
    category: 'unique',
    neighborhood: 'East Austin',
    address: '1103 E 6th St, Austin, TX 78702',
    description: 'Donation-based yoga studio on East 6th. All levels welcome.',
    source: 'word of mouth',
    dayTrip: false,
  },
  {
    id: 'old-taylor-high',
    name: 'Old Taylor High',
    lat: 30.5724, lng: -97.4165,
    category: 'unique',
    neighborhood: 'Taylor',
    address: '410 W 7th St, Taylor, TX 76574',
    description: '1923 school turned antique shops, restaurants, arcade. Worth the 40-min drive.',
    source: 'word of mouth',
    dayTrip: true,
  },
  {
    id: 'hanshin-pocha',
    name: 'Hanshin Pocha',
    lat: null, lng: null,
    category: 'unique',
    neighborhood: 'TBD',
    address: 'Austin location TBD',
    description: 'Korean bar food chain. Austin location announced but not yet open.',
    source: 'social media',
    dayTrip: false,
  },
  {
    id: 'phoebes-diner',
    name: "Phoebe's Diner",
    lat: 30.2420, lng: -97.7593,
    category: 'food',
    neighborhood: 'South Austin',
    address: '533 W Oltorf St, Austin, TX 78704',
    description: 'Southern comfort breakfast + BBQ. Biscuits and gravy heaven.',
    source: 'word of mouth',
    dayTrip: false,
  },
];
